# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f23fff05-2a99-4086-9865-4911a5280fc9";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5060-AC3F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    fileSystems."/mnt/win-d" = {
      device = "/dev/disk/by-uuid/F2C07986C07951B9";
      fsType = "ntfs3";
      options = [ "uid=1000" "gid=100" "umask=022" "nofail" "x-systemd.automount" ];
    };

    fileSystems."/mnt/win-small" = {
      device = "/dev/disk/by-uuid/25B569AE0C63D6C1";
      fsType = "ntfs3";
      options = [ "uid=1000" "gid=100" "umask=022" "nofail" "x-systemd.automount" ];
    };

    fileSystems."/mnt/win-c" = {
      device = "/dev/disk/by-uuid/17C1242D58741CE1";
      fsType = "ntfs3";
      options = [ "uid=1000" "gid=100" "umask=022" "nofail" "x-systemd.automount" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
